name: the-power-workflow-simple
on:
  workflow_call:
  repository_dispatch:
    types: [custom_event_type]
jobs:
  blank:
    runs-on: ubuntu-latest
    steps:
      - name: MyCommands
        run: |
          echo Hello
          echo World
